FROM python:3.11-slim

WORKDIR /app
ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

COPY pyproject.toml README.md ./
COPY datalus ./datalus
RUN pip install .

EXPOSE 8000
CMD ["uvicorn", "datalus.api:app", "--host", "0.0.0.0", "--port", "8000"]

