FROM python:3.11-slim

WORKDIR /app
ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

COPY pyproject.toml README.md ./
COPY src ./src
RUN pip install .

EXPOSE 8000
CMD ["uvicorn", "datalus.interfaces.api:app", "--host", "0.0.0.0", "--port", "8000"]
